# Generated by Django 2.0.13 on 2019-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0011_filtercategory_filtercategoryitem_filteritem'),
        ('materials', '0015_remove_material_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='materials', to='filters.MpttFilterItem'),
        ),
    ]
