# Generated by Django 2.0.13 on 2019-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_material_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='materials', to='filters.FilterItem'),
        ),
    ]
