# Generated by Django 2.0.13 on 2019-11-01 12:27

from django.db import migrations, models
import django_enumfield.db.fields
import surf.statusenums


class Migration(migrations.Migration):

    replaces = [('materials', '0019_auto_20191021_1326'), ('materials', '0020_auto_20191024_0939')]

    dependencies = [
        ('materials', '0018_auto_20190830_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='collection',
            name='publish_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=surf.statusenums.PublishStatus),
        ),
        migrations.AddField(
            model_name='collection',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
