# Generated by Django 2.0.13 on 2019-10-21 13:26

from django.db import migrations
import django_enumfield.db.fields
import surf.apps.materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_auto_20190830_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='collection',
            name='publish_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=surf.apps.materials.models.PublishStatus),
        ),
    ]
