# Generated by Django 2.0.13 on 2019-10-17 08:45

from django.db import migrations, models


def remove_themes_from_materials(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    for material in Material.objects.all():
        material.themes.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_auto_20190830_0934'),
    ]

    operations = [
        migrations.RunPython(remove_themes_from_materials, remove_themes_from_materials),
        migrations.AlterField(
            model_name='material',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='materials_mptt_disciplines', to='filters.MpttFilterItem'),
        ),
        migrations.AlterField(
            model_name='material',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='materials_mptt_themes', to='filters.MpttFilterItem'),
        ),
    ]
