# Generated by Django 2.0.13 on 2019-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20191021_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
