# Generated by Django 2.0.13 on 2019-10-17 08:59

from django.db import migrations
from surf.apps.materials.models import Material


def remove_themes_from_materials(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    for material in Material.objects.all():
        material.themes.clear()


def sync_all_material_info(apps, schema_editor):
    for material in Material.objects.all():
        material.sync_info()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20191017_0845'),
    ]

    operations = [
        migrations.RunPython(sync_all_material_info, remove_themes_from_materials)
    ]
