# Generated by Django 2.0.13 on 2019-11-01 12:36

from django.db import migrations, models
import django.db.models.deletion


def copy_materials_to_new_collections(apps, schema_editor):
    Collection = apps.get_model('materials', 'Collection')
    CollectionMaterial = apps.get_model('materials', 'CollectionMaterial')

    for collection in Collection.objects.all():
        for material in collection.materials.all():
            CollectionMaterial.objects.create(collection=collection, material=material)

        collection.save()


def remove_new_materials(apps, schema_editor):
    Collection = apps.get_model('materials', 'Collection')

    for collection in Collection.objects.all():
        collection.new_materials.clear()
        collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_replace_is_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
            options={
                'verbose_name': 'Material',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='new_materials',
            field=models.ManyToManyField(blank=True, related_name='new_collections', through='materials.CollectionMaterial', to='materials.Material'),
        ),
        migrations.RunPython(copy_materials_to_new_collections, remove_new_materials)
    ]
