# Generated by Django 2.0.13 on 2019-08-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_auto_20190829_1106'),
        ('themes', '0003_improved_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='filter_category_item',
        ),
        migrations.AddField(
            model_name='theme',
            name='filter_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.FilterItem'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.FilterItem'),
        ),
    ]
