# Generated by Django 2.0.13 on 2019-08-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0011_filtercategory_filtercategoryitem_filteritem'),
        ('themes', '0004_auto_20190819_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.MpttFilterItem'),
        ),
        migrations.AddField(
            model_name='theme',
            name='filter_category_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.MpttFilterItem'),
        ),
    ]
