# Generated by Django 2.0.13 on 2019-08-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_auto_20190819_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.FilterItem'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='filter_category_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.FilterItem'),
        ),
    ]
