# Generated by Django 2.0.13 on 2019-08-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20190819_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='filter_category_item',
            new_name='filter_item',
        ),
    ]
