version: '3.1'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - /docker/surf-backend/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=surf
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=surf
    healthcheck:
        test: psql -U surf surf -c "SELECT 'DBD::Pg ping test'"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=surf.settings.local
    volumes:
      - /volumes/surf/media:/src/media
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - postgres:database
    depends_on:
      - postgres
    restart: unless-stopped
