# Generated by Django 2.0.13 on 2019-11-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_setup_new_member_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='new_members',
            new_name='members',
        ),
        migrations.AddField(
            model_name='community',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='title_translations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.Locale'),
        ),
    ]
