# Generated by Django 2.0.13 on 2019-10-21 09:16

from django.db import migrations
import django_enumfield.db.fields
import surf.apps.communities.models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20191021_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='is_available',
        ),
        migrations.AddField(
            model_name='community',
            name='publish_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=surf.apps.communities.models.PublishStatus),
        ),
    ]
