# Generated by Django 2.0.13 on 2019-11-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_remove_old_member_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description_translations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.LocaleHTML'),
        ),
    ]
