# Generated by Django 2.0.13 on 2019-10-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_remove_community_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='new_members',
            new_name='members',
        ),
    ]
