# Generated by Django 2.0.13 on 2019-08-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20190819_0911'),
        ('materials', '0015_remove_material_disciplines'),
        ('filters', '0006_filtercategory_title_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtercategory',
            name='title_translations',
        ),
        migrations.RemoveField(
            model_name='filtercategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='category_item',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='filter',
        ),
        migrations.DeleteModel(
            name='FilterCategory',
        ),
        migrations.DeleteModel(
            name='FilterCategoryItem',
        ),
        migrations.DeleteModel(
            name='FilterItem',
        ),
    ]
