# Generated by Django 2.0.13 on 2019-08-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20190829_1106'),
        ('filters', '0007_auto_20190829_1106'),
        ('themes', '0004_auto_20190829_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterCategoryItem',
        ),
    ]
