# Generated by Django 2.0.13 on 2019-08-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_auto_20190819_0911'),
        ('filters', '0009_mpttfilteritem_is_hidden'),
    ]

    operations = [
    ]
