# Generated by Django 2.0.13 on 2019-08-19 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locale', '0004_improved_translations'),
        ('themes', '0006_auto_20190819_1243'),
        ('materials', '0017_auto_20190819_1243'),
        ('filters', '0011_filtercategory_filtercategoryitem_filteritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='filtercategory',
            name='title_translations',
        ),
        migrations.RemoveField(
            model_name='filtercategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mpttfilteritem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='mpttfilteritem',
            name='title_translations',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='category_item',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='filter',
        ),
        migrations.AddField(
            model_name='filteritem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='deleted_from_edurep_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='enabled_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Field id in EduRep'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default='default', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='name',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filters.FilterItem'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='title_translations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.Locale'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='FilterCategory',
        ),
        migrations.DeleteModel(
            name='FilterCategoryItem',
        ),
        migrations.DeleteModel(
            name='MpttFilterItem',
        ),
    ]
